### ISSUE TITLE
Failure to handle events processed by an IME

### ISSUE THREAD

**Issue by hey-cube** [viclafouch/mui-chips-input#11]
**Describe the bug**

Chip is added when I press `Enter` to confirm the conversion by an IME.

**To Reproduce**

1. Go to `https://viclafouch.github.io/mui-chips-input/`
2. Type Japanese (For example 'りんご')
3. Press `Enter` key

**Expected behavior**

Chips is not added during an IME processing.

**Screenshots**

https://user-images.githubusercontent.com/18608707/206427008-6e21a2e8-14ef-41ec-a2be-ced43dab01ea.mov

**Desktop**

 - OS: macOS Monterey (v12.6.1)
 - Browser: Google Chrome
 - Version: 108.0.5359.98

**Additional context**

PR is already ready.
Please close it if you don't need it.

Thank you for the wonderful library!

**Comment by viclafouch** [comment]
Hello @hey-cube !

Thanks a lot for your help ! 

PR approved and merged. Released in https://github.com/viclafouch/mui-chips-input/releases/tag/v1.3.2

Thannnks :)
