### ISSUE TITLE
Expected hoisted manifest when trying to install with yarn and @emotion/react version 11.10.4

### ISSUE THREAD

**Issue by arunlodhi** [viclafouch/mui-chips-input#13]
When trying to install in a project with `"@emotion/react": "11.10.4"`,

`yarn add mui-chips-input`

fails throwing the error:

```expected hoisted manifest for "mui-chips-input#@mui/material#@emotion/styled"```

**Steps to reproduce the behavior:**
```
git clone 'https://github.com/arunlodhi/mui-chips-input-error'

yarn install

yarn add mui-chips-input
```

**Comment by arunlodhi** [comment]
I was able to install `mui-chips-input` by updating my `@emotion/react` and `@emotion/styled` packages to version `11.10.5` in package.json.

Feel free to close the issue,

**Comment by viclafouch** [comment]
Let's close until someone have the same problem.
