### ISSUE TITLE
Is there a way to force the chips values to be unique?

### ISSUE THREAD

**Issue by ErezBiren** [viclafouch/mui-chips-input#15]
Hi. 

**Is your feature request related to a problem? Please describe.**
I need the chips to be unique so every chip text will appear only once.

**Describe the solution you'd like**
A new property that set the uniqueness true\false. (although I can't think why someone would like it to be not unique)

**Comment by viclafouch** [comment]
You can use the `validate` prop and check if the value exists in your array
