### ISSUE TITLE
Warning: A props object containing a "key" prop is being spread into JSX

### ISSUE THREAD

**Issue by thaihuyhung** [viclafouch/mui-chips-input#17]
**Describe the bug**
Hi, I'm having this warning every time I add new item into input
**To Reproduce**
1. Click on input
2. Type anything and press enter
3. The warning is shown in console
Error from file: https://github.com/viclafouch/mui-chips-input/blob/main/src/components/TextFieldChip/TextFieldChips.tsx#L304

**Expected behavior**
No error is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/20571796/218284554-0c72eea1-5ece-4a8b-9e20-be6e3715ed3a.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by viclafouch** [comment]
Hello @thaihuyhung !

Thanks for the catch !

Fixed in https://github.com/viclafouch/mui-chips-input/releases/tag/v2.0.0
