### ISSUE TITLE
inputRef is always null

### ISSUE THREAD

**Issue by anavalo** [viclafouch/mui-chips-input#19]
**Describe the bug**
If you pass an `inputRef` in `MuiChipsInput,` it is always null. It's `current` value doesn't take the input. 

**To Reproduce**
Pass an inputRef in MuiChipInput and log it.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ventura 13
 - Browser: Chrome
 - Version 106

**Smartphone (please complete the following information):**

**Additional context**

**Comment by viclafouch** [comment]
You can simply pass the ref prop to the component. It's the same as inputRef here. 

But I've still released the fix : https://github.com/viclafouch/mui-chips-input/releases/tag/v2.0.1
