### ISSUE TITLE
Add Start and End Adornments to mui-chips-input

### ISSUE THREAD

**Issue by harmanbirdi** [viclafouch/mui-chips-input#2]
**Is your feature request related to a problem? Please describe.**
I am trying to implement a mui-chips-input where an action needs to be taken on those items.

**Describe the solution you'd like**
Instead of just text, I want to be able to use this for emails, and would like to be able to include
SendIcon to be able to take send email action on it.  To be able to provide email validation
and max items that can be added would also be great.

**Describe alternatives you've considered**
I tried converting a react solution to mui-chip solution, which does most of the the work, except
it puts the chips above the textfield instead of inside the textfield. I would like for them to be 
inside the textfield.

**Additional context**
None

**Comment by viclafouch** [comment]
Hello @harmanbirdi 

Thanks a lot for your feedback ! 

Something like that ? 

```js
<MuiChipsInput renderChip={(Component, props) => {
  return <Component {...props} icon={<FaceIcon />} />
}} />

```

<img width="473" alt="image" src="https://user-images.githubusercontent.com/23353836/189841455-0cfac2d8-5dbc-4538-bf20-ef7bd4111e6f.png">

What about only Start Adornments, because if you replace the endAdornments, you will not able to remove a chip..

**Comment by harmanbirdi** [comment]
Hello Victor,

Thank you for your quick response.   So, what I am gathering is that you
are using the EndAdornment in
the Chip for the X icon in order to close it.  Is that correct?

However, I also see the second X, which is used to clear all of the chips
that are currently in there.
Is it possible for that to be replaced or customized, by another
EndAdornment.   You could default
it to the X that is there right now, or have it be overridden by another
icon and action.

Hope that makes sense.

Regards,
--H

**Comment by viclafouch** [comment]
Ok you can override with this solution that I will release : 

```js
<MuiChipsInput renderChip={(Component, props) => {
  return <Component {...props} deleteIcon={<FaceIcon />} />
}} />

```

**Comment by harmanbirdi** [comment]
@viclafouch - I also wanted to check with you on one other thing. You mentioned the above to override deleteIcon
with any icon you wish, but what about the associated action.  I would not want to clear out the current contents of
MuiChipsInput when I click FaceIcon.

Like I had mentioned, I want to be able to send out emails, so I have to call out my own action. I still may choose to
empty out the MuiChipsInput field as part of that.  Hope that helps.

Still learning so please pardon my ignorance, if that is something that can already be done.

**Comment by viclafouch** [comment]
Like that ? 

```tsx
<MuiChipsInput renderChip={(Component, props) => {
  return <Component {...props} deleteIcon={<FaceIcon />} onDelete={overrideHere} />
}} />
```

**Comment by harmanbirdi** [comment]
Hi Victor,

This is what I am trying but it is not working.

<MuiChipsInput
value={chips}
onChange={handleChange1}
style={{ width: '90%' }}
renderChip={(Component, props) => {
return <Component {...props} deleteIcon={<SendIcon />} onDelete={
overrideHere} />;
}}
/> The SendIcon fails to render inside the MuiChipsInput (bottom). I have
the top one in which I have placed the SendIcon outside independently of
MuiChipsInput field. [image: image.png]
Not certain if I am doing this correctly. Are you planning to make this as
an enhancement
or you just responded to me with a possible solution. Thank you,
--H

**Comment by viclafouch** [comment]
I did not release yet ahah

**Comment by viclafouch** [comment]
Hey ! 1.2.0 is now available.

https://viclafouch.github.io/mui-chips-input/docs/api-reference/#renderchip

**Comment by harmanbirdi** [comment]
Hello Victor,

Thank you - I will update to the latest version and try it out.
However, the link you included -
https://viclafouch.github.io/mui-chips-input/docs/api-reference/#renderchip
is giving me a 404 error.

Regards,
--H

**Comment by viclafouch** [comment]
Fixed sorry ^^

**Comment by harmanbirdi** [comment]
Hi Victor,

Thank you so much for helping take care of this. Hope this works as
intended.
Apologies for the delay in response, but it was night time here, so I have
called
it a night.

Regards,
--Harman
