### ISSUE TITLE
[Bug fix] entering chip on mobile in form does not work

### ISSUE THREAD

**Issue by BennyAlex** [viclafouch/mui-chips-input#24]
@viclafouch Hey, it's me again :P

When the chips input is inside an form, it's impossible to add a chip, since touching on the enter key will go to the next field instead by default.
Here is a fix: 
```
inputProps={{
        enterkeyhint: 'done'
      }}
```

since this is a common case this should be included by default.

**Comment by viclafouch** [comment]
Hello @BennyAlex ! 

Could you please share a codesandbox in order to test it on my mobile plz ?

Thanks!

**Comment by albertus-andito** [comment]
> ```
> inputProps={{
>         enterkeyhint: 'done'
>       }}
> ```
> 

While this generally works, seems like it doesn't work for all mobiles?

**Comment by BennyAlex** [comment]
@viclafouch 
here is an example. First one doesnt allow to enter a chip, with the fix it is possible.
https://codesandbox.io/s/mui-chips-input-forked-wre96y?file=/src/App.js

@albertus-andito 
what do you mean exactly? 
@viclafouch maybe there has to be another enter key detection to be implemented
