### ISSUE TITLE
Add chip on the click of tab

### ISSUE THREAD

**Issue by januhub** [viclafouch/mui-chips-input#25]
**Describe the bug**
After typing the email if I click the tab chip is not getting added even after adding 'Tab' in the addOnWhichKey Options

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/61153365/230028757-3896f3fa-dd33-4279-bc0b-6ee6e0bbb56a.png">

**To Reproduce**
[Codesandbox code](https://codesandbox.io/s/mui-chips-input-forked-2ul57e)

**Expected behavior**
If we keypress 'Tab' text should become chip in the input box

**Additional context**

**Comment by viclafouch** [comment]
Fixing it...
