### ISSUE TITLE
Cannot import dependencies in lazy loaded pages especially in build environment

### ISSUE THREAD

**Issue by rlaqltmxm** [viclafouch/mui-chips-input#26]
**Describe the bug**

`mui-chips-input` seems to be not able to import dependencies in lazy loaded pages
Runtime error occurs and getting white page with following error

<img width="570" alt="스크린샷 2023-04-17 오후 9 30 49" src="https://user-images.githubusercontent.com/44524767/232484637-ed25a903-e62e-4a87-baf2-3fc64cf56557.png">

**To Reproduce**
Preconditions
- lazy loaded pages using `React.lazy`
- `process.env.NODE_ENV = 'production'`
- works well in index page, but **not in routing pages**
- build tool: esbuild

Fixes
- I removed lazy import to fix temporarily, It works well as I expected

**Expected behavior**
Occurs none of errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [106.0.5249.119]

**Smartphone (please complete the following information):**
- Not mobile targeted

**Additional context**
If you need any additional context for reproducing the behavior, please feel free to request

**Comment by viclafouch** [comment]
Hello ! 

Could you provide a codesandbox plz ?

**Comment by rlaqltmxm** [comment]
Hello, 
This bug is not reproduced when configured in the other independent environment. There seems to be a problem with development environment I'm working.. 🤔 
I will reopen this issue when the occurrence condition is specified. Thank you!
