### ISSUE TITLE
loader issue

### ISSUE THREAD

**Issue by kswat** [viclafouch/mui-chips-input#31]
**Describe the bug**

Loader error

./node_modules/mui-chips-input/dist/mui-chips-input.es.js 56:10
Module parse failed: Unexpected token (56:10)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
**To Reproduce**
1. use latest

**Expected behavior**
compile without issues

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome

**Comment by bthomasstill** [comment]
On the latest version and seem to be having the same loader issue--

```
node_modules/mui-chips-input/dist/mui-chips-input.es.js 44:6
Module parse failed: Unexpected token (44:6)
File was processed with these loaders:
 * ../../node_modules/source-map-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     d.key === O.enter && r(i);
|   }, A = (d) => {
>     d?.preventDefault?.(), d?.stopPropagation?.(), r(i);
|   }, b = (d) => {
|     d.target.textContent === y.label && (s || g(i));
```

Was there an easy fix for this?

**Comment by viclafouch** [comment]
Your config need to handle optional chaining (eg: `foo?.bar`)
