### ISSUE TITLE
ERROR in ./node_modules/mui-chips-input/dist/mui-chips-input.es.js 259:28-30 export 'default' (imported as 'gt') was not found in '@mui/base/ClickAwayListener' (possible exports: ClickAwayListener)

### ISSUE THREAD

**Issue by lokemass** [viclafouch/mui-chips-input#35]
**Describe the bug**
today I got this error before it works fine

**To Reproduce**
1. just I run npm install 
2.  this error arise

**Desktop (please complete the following information):**
 - OS: windows 10
 -     "mui-chips-input": "^2.0.2",

**Additional context**
ERROR in ./node_modules/mui-chips-input/dist/mui-chips-input.es.js 259:28-30
export 'default' (imported as 'gt') was not found in '@mui/base/ClickAwayListener' (possible exports: ClickAwayListener)

**Comment by viclafouch** [comment]
Hello ! 

Could you try installing `@mui/base` plz ?

```
npm i @mui/base
```

**Comment by Silur** [comment]
same issue with @mui/base being `^5.0.0-beta.10`

**Comment by viclafouch** [comment]
Could you please share me a codesandbox with the issue plz ?

**Comment by DinhHoang47** [comment]
> same issue with @mui/base being `^5.0.0-beta.10`

+ 1 vote. I have the same problem.

**Comment by ptah0** [comment]
Here is the example: https://codesandbox.io/s/mui-chip-input-trjzg8?file=/package.json
It's related to the `@mui/material` in package.json
It's working when `"@mui/material": "~5.13.7",`
but not working when `"@mui/material": "~5.14.3",`

**Comment by viclafouch** [comment]
Fixed in `2.1.3`
