### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ryan-bytesquid** [viclafouch/mui-chips-input#36]
**Describe the bug**
When running tests in jest on version 2.1.3 I get the error "SyntaxError: Cannot use import statement outside a module"
This problem appears to have have come up in v2.1.2 where the UMD modules were removed.

Jest.config.js
```
module.exports = {
    transform: {
        '^.+\\.(js|jsx|ts|tsx)$': [
            'babel-jest',
            { configFile: './testConfig/babel.config.json' }
        ]
    },
    transformIgnorePatterns: ['/node_modules/(?!mui-chips-input)'],
    setupFilesAfterEnv: ['./testConfig/setupTests.js'],
    testEnvironment: 'jsdom',
    collectCoverage: true,
    collectCoverageFrom: [
        'src/**/*.{js,jsx}',
        '!src/index.jsx',
        '!src/utils/theme/**',
        '!**/node_modules/**',
        '!**/vendor/**'
    ],
    clearMocks: true,
    coverageThreshold: {
        global: {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100
        }
    },
    moduleNameMapper: {
        '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
            '<rootDir>/__mocks__/fileMock.js',
        '\\.(css|less)$': '<rootDir>/__mocks__/fileMock.js'
    }
};
```

babel.config.json
```
{
    "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

**To Reproduce**
Run a test with the given jest config and mui-chips-input

**Expected behavior**
test should pass

**Screenshots**
![image](https://github.com/viclafouch/mui-chips-input/assets/129431076/4863f82e-827c-4246-83aa-7acadd1c5715)

**Desktop:**
 - OS: Ubuntu
 - Version 22.04

**Comment by Silur** [comment]
same issue on versions from 2.0.2 up to 2.1.3

**Comment by viclafouch** [comment]
Hello ! 

This package is an ESM package, check this : https://jestjs.io/docs/ecmascript-modules

**Comment by sprockow** [comment]
Hi @viclafouch - I think one of the issues might be that the library's package.json does not have a `"type": "module"` . Next.js complains about this as well when resolving the dependency. It throws an error that it encountered an unexpected import statement (because it believes it to be a commonjs dependency).

**Comment by sprockow** [comment]
I forked and pull down the repo, and found out that switching the package.json type to module breaks things with several build tools ( ESM vs CommonJS issues will be the death of me...). 

So, my alternative solution would be to build a commonjs output alongside the esm output. This is easy enough to do with vite, and I can stage a PR if you're not against the idea.

I tested this out, and next js no longer blows up when resolving the library. This would unblock me to being able to use some of the newer features, like the `addOnBlur` prop.

Thoughts?

**Comment by viclafouch** [comment]
Hello @sprockow !

Did you try this alternative : https://github.com/viclafouch/mui-tel-input/issues/84#issuecomment-1760126480

Ty

**Comment by sprockow** [comment]
Thanks the quick replay and for pointing that solution out. That should work as a workaround for now.

**Comment by master117** [comment]
> Hello @sprockow !
> 
> Did you try this alternative : [viclafouch/mui-tel-input#84 (comment)](https://github.com/viclafouch/mui-tel-input/issues/84#issuecomment-1760126480)
> 
> Ty

I'm facing this issue while running jest and I can not clear my transform as is described here: https://jestjs.io/docs/ecmascript-modules

So sadly neither of these solutions work for me.

**Comment by Destaby** [comment]
> I'm facing this issue while running jest and I can not clear my transform as is described here: https://jestjs.io/docs/ecmascript-modules
So sadly neither of these solutions work for me.

Same for me. Is there an update?
