### ISSUE TITLE
Cannot use InputProps with Chip Input

### ISSUE THREAD

**Issue by monicayao** [viclafouch/mui-chips-input#38]
**Describe the bug**
When using `InputProps`, chips do not properly show up. 
I saw that this inherits from `TextField`, https://viclafouch.github.io/mui-chips-input/docs/inheritance/
so it should also inherit `InputProps`, one of them being an adornment.

**To Reproduce**
I made a sandbox of this behavior 
https://codesandbox.io/embed/inspiring-http-dn7gxh?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
When there is an input adornment the chips should still show up.

**Screenshots**

https://github.com/viclafouch/mui-chips-input/assets/35382166/46aa382d-9f16-47f5-a48f-544a300ec9da

**Desktop (please complete the following information):**
 - macOS
- chrome
 - Version 117

**Comment by viclafouch** [comment]
Hello ! 

Sorry for the delay. You can't add a `startAdornment` to this component add it will result to unexpected behaviors in UI level..
