### ISSUE TITLE
Custom Style Help 

### ISSUE THREAD

**Issue by leeyucha** [viclafouch/mui-chips-input#40]
Hello, Nice to meet you.

First of all, Thanks for your software.
It's great and working very well.

But I have difficulty adjusting MUI Joy design system to mui-chips-input. 
Could you give me any idea or some advice for this.

I'd like to make mui-chips-inputs look liks Joy Input Component.

Thank you

**Comment by viclafouch** [comment]
Hello ! 

I don't think this library is compatible with Joy. sorry :/

**Comment by leeyuchang** [comment]
Hi @viclafouch 
Thanks for your feed back.
I have just changed the UI package from JOY to MUI.
As the result, it's no problem now. ^^
