### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by 0x0elliot** [viclafouch/mui-chips-input#41]
**Describe the bug**
When I try to Transpile my code, the snippet with this library being imported starts to break!

**To Reproduce**
1. Write code
2. Transpile for SSR with babel
3. Run the express server
4.  You end up with something like this pretty soon
![image](https://github.com/viclafouch/mui-chips-input/assets/60684641/dd55d31b-028f-4416-8408-f77536dd2076)

**Comment by viclafouch** [comment]
Hello ! 

You have to transpile the library as it is an ESM package.
