### ISSUE TITLE
Feature Request: Autocomplete

### ISSUE THREAD

**Issue by ozomer** [viclafouch/mui-chips-input#42]
**Is your feature request related to a problem? Please describe.**
Sometimes the values that the user can select, or usually selects, is from a list of options. An autocomplete feature would be nice.

**Describe the solution you'd like**
While the user fills the input, a menu pops below the text-input with values that have the same prefix (up to five values).

**Describe alternatives you've considered**
https://www.npmjs.com/package/react-tag-input
https://mui.com/material-ui/react-autocomplete/#customized-hook

**Comment by viclafouch** [comment]
Hello ! 

MUI Doc provides everything u need here : https://mui.com/material-ui/react-autocomplete/#multiple-values
