### ISSUE TITLE
Request for official documentation on the `addOnWhichKey` attribute.

### ISSUE THREAD

**Issue by ynng3** [viclafouch/mui-chips-input#48]
I was developing a feature to automatically add items to an array when a comma is input. During this process, I opened the module and discovered that this functionality is already possible through this attribute.

However, the official documentation does not mention this attribute for the component, which poses a risk of unnecessary development for users.

I also developed unnecessary code since I was unaware of this feature, and then had to delete it. I hope this component attribute will be included in the official documentation.

**Comment by ynng3** [comment]
#50 I simply wanted to request the addition of documentation from the creator, but I learned that it is possible to make a Pull Request for the documentation, so I directly made a Pull Request for the issue.

**Comment by viclafouch** [comment]
Hello ! 

Sorry for the documentation, looks like I forgot to mention this feature ahah.

Thanks anyway !
