### ISSUE TITLE
Unable to use MuiChipsInput with React 18, node 20 and @mui/material v6

### ISSUE THREAD

**Issue by akshay-hulkuli** [viclafouch/mui-chips-input#52]
Whenever we try to import the MuiChipsInput 
`import { MuiChipsInput } from 'mui-chips-input';`

getting exception -> 
```
ERROR in ./node_modules/mui-chips-input/dist/mui-chips-input.es.js 3:0-36
Module not found: Error: Can't resolve '@mui/material/Chip' in '/home/akshaya/learning/react/project-migrations/my-app/node_modules/mui-chips-input/dist'
Did you mean 'index.js'?
BREAKING CHANGE: The request '@mui/material/Chip' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

React version -> 18.3.1
Node version -> v20.18.0
@mui/material -> 6.1.6
mui-chips-input -> 3.1.1

**Comment by ynng3** [comment]
Thanks for leaving an issue.

After looking into the code, I found out that the `"type": "module"` option in `node_modules/mui-chips-input/package.json` forces mui-chips-input to input the `.js` extension when using the `import` statement.

mui-chips-input uses that option, but for some reason doesn't specify the extension.

I have identified this issue and will request a PR as soon as possible.

If this setting is necessary or my PR request is not appropriate, you and I may have to wait for the original developer to provide a correct patch.

@akshay-hulkuli @viclafouch
