### ISSUE TITLE
Make chips draggable

### ISSUE THREAD

**Issue by lashax** [viclafouch/mui-chips-input#8]
It would be a good idea to make the chip draggable, so the order could be changed. See the example from _Gmail_:

![image](https://user-images.githubusercontent.com/20067025/195625602-1f1568e9-310e-4986-9c93-7388cfd1dc6a.png)

**Comment by viclafouch** [comment]
Hello ! 

Good feature but as it is a big feature, I want to wait for more feedback from developers about this. I keep this issue opened.

**Comment by jadus** [comment]
Hi
I would use this feature for sure

**Comment by wilyanto** [comment]
Yesh, I would to have this kind of feature too.. because when in edit mode, the user might need to re-adjust the order of the chips 🙏
